name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${project.author}
main: de.derfrzocker.fast.worldborder.fill.FastWorldBorderFill
api-version: "1.14"
commands:
  fast-fill:
    permission: fast.fill